Employee/Models/AddEmploye.cs
namespace Employee.Models
{
    public class AddEmploye
    {
        public string Name { get; set; }


        public int age { get; set; }

        public string jobTitle { get; set; }
        public DateTime start { get; set; }
        public DateTime end { get; set; }

        public string previousPosition { get; set; }

        public string companyName { get; set; }

        public DateTime pStart { get; set; }
        public DateTime pEnd { get; set; }
    }
}

Employee/Models/ErrorViewModel.cs
namespace Employee.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Employee/Models/UpdateEmployeeViewModel.cs
namespace Employee.Models
{
    public class UpdateEmployeeViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }


        public int age { get; set; }

        public string jobTitle { get; set; }
        public DateTime start { get; set; }
        public DateTime end { get; set; }

        public string previousPosition { get; set; }

        public string companyName { get; set; }

        public DateTime pStart { get; set; }
        public DateTime pEnd { get; set; }
    }
}

Employee/Models/employee.cs
using System.ComponentModel.DataAnnotations;

namespace Employee.Models
{
    public class employee
    {
        [Key]
        public Guid Id { get; set; }        
        public string Name { get; set; }
        
    
        public int age { get; set; }

        public string jobTitle { get; set; }
        public DateTime start { get; set; }
        public DateTime end { get; set; }
        
        public string previousPosition { get; set; }

        public string companyName { get; set; }

        public DateTime pStart { get; set; }
        public DateTime pEnd { get; set; }

    }
}

Employee/Controllers/EmpController.cs
using Employee.Data;
using Employee.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Employee.Controllers
{
    public class EmpController : Controller
    {
        private readonly ApplicationDbContext newDB;

        public EmpController(ApplicationDbContext newDB)
        {
            this.newDB = newDB;
        }


        [HttpGet]
        public async Task<IActionResult> Index()
        {
         var employee = await newDB.Employees.ToListAsync();
            return View(employee);  
        }



        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddEmploye addEmployeRequest)
        {
            var employee = new employee()
            {
                Id = Guid.NewGuid(),
                Name = addEmployeRequest.Name,
                age = addEmployeRequest.age,
                jobTitle = addEmployeRequest.jobTitle,
                start = addEmployeRequest.start,
                end = addEmployeRequest.end,
                companyName= addEmployeRequest.companyName,
                previousPosition = addEmployeRequest.previousPosition,
                pStart = addEmployeRequest.pStart,
                pEnd = addEmployeRequest.pEnd,
            };
            await newDB.Employees.AddAsync(employee);
            await newDB.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {

            var employee = await newDB.Employees.FirstOrDefaultAsync(x => x.Id == id);
           if(employee != null)
            {
                var viewModel = new UpdateEmployeeViewModel()
                {
                    Id = employee.Id,
                    Name = employee.Name,
                    age = employee.age,
                    jobTitle = employee.jobTitle,
                    start = employee.start,
                    end = employee.end,
                    companyName = employee.companyName,
                    previousPosition = employee.previousPosition,
                    pStart = employee.pStart,
                    pEnd = employee.pEnd,

                };
                return await Task.Run(()=>View("View",viewModel));

            }

            return RedirectToAction("Index");

        }
        [HttpPost]
        public async Task<IActionResult> View(UpdateEmployeeViewModel model) 
        {
            var employee = await newDB.Employees.FindAsync(model.Id);

            if (employee != null) 
            {

                employee.Id = model.Id;
                employee.Name=model.Name;
                employee.age = model.age;
                employee.jobTitle = model.jobTitle;
                employee.start = model.start;
                employee.end = model.end;
                employee.companyName = model.companyName;
                employee.previousPosition = model.previousPosition;
                employee.pStart = model.pStart;
                employee.pEnd = model.pEnd;

                await newDB.SaveChangesAsync();

                return RedirectToAction("Index");

            }
            return RedirectToAction("Index");


        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateEmployeeViewModel model) 
        {
            var employee = await newDB.Employees.FindAsync(model.Id);
            if (employee != null) 
            {
                newDB.Employees.Remove(employee);
                await newDB.SaveChangesAsync();
                return RedirectToAction("Index");

            }
            return RedirectToAction("Index");
            

        }

    }


}

Employee/Controllers/HomeController.cs
using Employee.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Employee.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Employee/Views/Emp/Add.cshtml
@model Employee.Models.AddEmploye

@{
}
<h1> Add employee</h1>
<form method="post" action="Add" class="mt-5">
  <div class="mb-3">
    <label for="">Name</label>
    <input type="text" class="form-control" asp-for="Name">
  </div>
    <div class="mb-3">
        <label for="">age</label>
        <input type="number" class="form-control" asp-for="age">
    </div>
    <div class="mb-3">
        <label for="">jobTitle</label>
        <input type="text" class="form-control" asp-for="jobTitle">
    </div>
    <div class="mb-3">
        <label for="">start</label>
        <input type="date" class="form-control" asp-for="start">
    </div>
    <div class="mb-3">
        <label for="">end</label>
        <input type="date" class="form-control" asp-for="end">
    </div>
    <div class="mb-3">
        <label for="">previousPosition</label>
        <input type="text" class="form-control" asp-for="previousPosition">
    </div> 
    <div class="mb-3">
        <label for="">companyName</label>
        <input type="text" class="form-control" asp-for="companyName">
    </div>
    <div class="mb-3">
        <label for="">pStart</label>
        <input type="date" class="form-control" asp-for="pStart">
    </div>
    <div class="mb-3">
        <label for="">pEnd</label>
        <input type="date" class="form-control" asp-for="pEnd">
    </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

Employee/Views/Emp/Index.cshtml
@model List<Employee.Models.employee>

@{
}


<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>AGE</th>
            <th>Job Title</th>
            <th>start</th>
            <th>end</th>
            <th>Experience</th>
            <th>companyName</th>
            <th>start</th>
            <th>End</th>
            <th>  </th>
        </tr>
    </thead>
    <tbody>
    @foreach(var employee in Model)
    {
        <tr>
            <td>@employee.Id</td>
            <td>@employee.Name</td>
            <td>@employee.age</td>
            <td>@employee.jobTitle</td>
            <td>@employee.start.ToString("dd-MM-yyyy")</td>
            <td>@employee.end.ToString("dd-MM-yyyy")</td>
            <td>@employee.previousPosition</td>
            <td>@employee.companyName</td>
            <td>@employee.pStart.ToString("dd-MM-yyyy")</td>
            <td>@employee.pEnd.ToString("dd-MM-yyyy")</td>
            <td><a href="Emp/View/@employee.Id"> VIEW </a></td>


        </tr>
    }
    </tbody>
</table>

Employee/Views/Emp/View.cshtml
@model Employee.Models.UpdateEmployeeViewModel
@{
}
<h1> Update employee Data</h1>
<form method="post" action="Add" class="mt-5">
    <div class="mb-3">
        <label for="">Name</label>
        <input type="text" class="form-control" asp-for="Id" readonly>
    </div>
    <div class="mb-3">
        <label for="">Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>
    <div class="mb-3">
        <label for="">age</label>
        <input type="number" class="form-control" asp-for="age">
    </div>
    <div class="mb-3">
        <label for="">jobTitle</label>
        <input type="text" class="form-control" asp-for="jobTitle">
    </div>
    <div class="mb-3">
        <label for="">start</label>
        <input type="date" class="form-control" asp-for="start">
    </div>
    <div class="mb-3">
        <label for="">end</label>
        <input type="date" class="form-control" asp-for="end">
    </div>
    <div class="mb-3">
        <label for="">previousPosition</label>
        <input type="text" class="form-control" asp-for="previousPosition">
    </div>
    <div class="mb-3">
        <label for="">companyName</label>
        <input type="text" class="form-control" asp-for="companyName">
    </div>
    <div class="mb-3">
        <label for="">pStart</label>
        <input type="date" class="form-control" asp-for="pStart">
    </div>
    <div class="mb-3">
        <label for="">pEnd</label>
        <input type="date" class="form-control" asp-for="pEnd">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Employee/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Employee/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Employee.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employee</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emp" asp-action="Add">Add employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emp" asp-action="Index">Show employee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Employee - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>